/**
 * Demo data — hardcoded, no Supabase, no private user data.
 * Used only by /demo/* routes.
 */
import type { Recipe, NutritionTargets } from '@/types'

export const DEMO_TARGETS: NutritionTargets = {
  calories: 2070,
  protein_min: 130,
  protein_target: 160,
  protein_max: 180,
}

// Realistic recipes spanning 200–700 kcal so calorie band filtering is obvious
export const DEMO_RECIPES: Recipe[] = [
  {
    id: 'demo-1',
    name: 'Emergency Max Protein',
    category: 'snack',
    description: 'Tuna + skyr side by side. 46g protein in under 300 kcal.',
    image_url: null,
    instructions: ['Drain tuna tin.', 'Spoon 200g skyr next to it.', 'Season with pepper and lemon.', 'Eat.'],
    prep_time_min: 2,
    cook_time_min: 0,
    total_time_min: 0,
    servings: 1,
    equipment_required: [],
    suitable_contexts: ['emergency_protein', 'snack', 'no_cooking'],
    suitable_times: ['post_gym', 'late_night'],
    stores_required: ['coop', 'migros'],
    tags: ['emergency-protein', 'no-cook', 'high-protein'],
    total_calories: 275,
    total_protein: 46,
    total_carbs: 8,
    total_fat: 2,
    estimated_price_chf: 4.20,
    protein_efficiency: 16.7,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-2',
    name: 'Quark Chocolate Mousse',
    category: 'snack',
    description: 'Magerquark with cocoa and honey. Tastes like dessert, 26g protein.',
    image_url: null,
    instructions: ['Mix 250g Magerquark with 1.5 tbsp cocoa, 2 tsp honey, pinch of salt.', 'Stir until smooth.', 'Top with raspberries.'],
    prep_time_min: 3,
    cook_time_min: 0,
    total_time_min: 0,
    servings: 1,
    equipment_required: [],
    suitable_contexts: ['snack', 'sweet', 'no_cooking'],
    suitable_times: ['late_night', 'breakfast'],
    stores_required: ['coop', 'migros'],
    tags: ['quark', 'sweet', 'no-cook', 'high-protein'],
    total_calories: 240,
    total_protein: 26,
    total_carbs: 28,
    total_fat: 3,
    estimated_price_chf: 2.80,
    protein_efficiency: 10.8,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-3',
    name: 'Skyr Berry Parfait',
    category: 'snack',
    description: 'Skyr layered with berries and granola. High protein, actually enjoyable.',
    image_url: null,
    instructions: ['Layer 150g skyr in a glass.', 'Add frozen berries (microwaved 30 sec).', 'Top with a handful of granola.', 'Drizzle with honey.'],
    prep_time_min: 3,
    cook_time_min: 0,
    total_time_min: 0,
    servings: 1,
    equipment_required: ['microwave'],
    suitable_contexts: ['snack', 'sweet', 'no_cooking'],
    suitable_times: ['breakfast', 'lunch'],
    stores_required: ['coop', 'migros'],
    tags: ['skyr', 'sweet', 'no-cook', 'high-protein'],
    total_calories: 320,
    total_protein: 28,
    total_carbs: 38,
    total_fat: 4,
    estimated_price_chf: 4.20,
    protein_efficiency: 8.8,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-4',
    name: 'Tuna Melt on Toast',
    category: 'lunch',
    description: 'Tuna with melted cheese on toast, grilled 3 minutes. 42g protein.',
    image_url: null,
    instructions: ['Mix drained tuna with a squeeze of lemon, salt, pepper.', 'Spread on 2 slices of toast.', 'Top with cheese slices.', 'Grill 3 min until bubbling.'],
    prep_time_min: 4,
    cook_time_min: 4,
    total_time_min: 8,
    servings: 1,
    equipment_required: ['oven'],
    suitable_contexts: ['meal', 'snack'],
    suitable_times: ['lunch', 'late_night'],
    stores_required: ['coop', 'migros'],
    tags: ['tuna', 'toast', 'quick', 'high-protein'],
    total_calories: 410,
    total_protein: 42,
    total_carbs: 28,
    total_fat: 12,
    estimated_price_chf: 4.80,
    protein_efficiency: 10.2,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-5',
    name: 'Creamy Scrambled Eggs on Toast',
    category: 'breakfast',
    description: 'Slow-cooked silky eggs on toast. 30g protein, 7 minutes.',
    image_url: null,
    instructions: ['Crack 4–5 eggs into a cold pan with butter and salt.', 'Medium-low heat — stir constantly until soft curds form (4–5 min).', 'Pull off heat when still slightly wet.', 'Serve on 2 slices of toast.'],
    prep_time_min: 1,
    cook_time_min: 6,
    total_time_min: 7,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['breakfast', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['eggs', 'breakfast', 'quick', 'high-protein'],
    total_calories: 380,
    total_protein: 30,
    total_carbs: 24,
    total_fat: 16,
    estimated_price_chf: 3.50,
    protein_efficiency: 7.9,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-6',
    name: 'Protein Pancakes',
    category: 'breakfast',
    description: 'Oat and skyr pancakes that taste like real pancakes. 40g protein.',
    image_url: null,
    instructions: ['Blend 80g oats, 3 eggs, 150g skyr, 0.5 tsp baking powder, pinch of salt.', 'Cook in an oiled pan on medium heat, 2–3 min per side.', 'Serve with yoghurt, honey, berries.'],
    prep_time_min: 5,
    cook_time_min: 12,
    total_time_min: 17,
    servings: 1,
    equipment_required: ['pan', 'blender'],
    suitable_contexts: ['meal'],
    suitable_times: ['breakfast', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['pancakes', 'breakfast', 'high-protein', 'skyr'],
    total_calories: 490,
    total_protein: 40,
    total_carbs: 52,
    total_fat: 10,
    estimated_price_chf: 4.50,
    protein_efficiency: 8.2,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-7',
    name: 'Greek Chicken Wrap',
    category: 'lunch',
    description: 'Marinated chicken with garlic skyr sauce in a tortilla. 48g protein.',
    image_url: null,
    instructions: ['Coat sliced chicken in oregano, paprika, lemon, oil. Pan-fry 5 min.', 'Mix skyr with garlic, lemon, salt for the sauce.', 'Warm tortilla 30 sec in dry pan.', 'Spread sauce, add chicken, cucumber, tomato. Roll and cut.'],
    prep_time_min: 8,
    cook_time_min: 8,
    total_time_min: 16,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['lunch', 'dinner'],
    stores_required: ['coop', 'migros'],
    tags: ['chicken', 'wrap', 'greek', 'quick', 'high-protein'],
    total_calories: 530,
    total_protein: 48,
    total_carbs: 44,
    total_fat: 12,
    estimated_price_chf: 6.40,
    protein_efficiency: 9.1,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-8',
    name: 'Chicken Teriyaki Rice Bowl',
    category: 'dinner',
    description: 'Sticky teriyaki chicken on rice. Made from scratch in 23 minutes. 52g protein.',
    image_url: null,
    instructions: ['Cook 150g rice (bring to boil, lid on, lowest heat, 12 min).', 'Slice chicken, fry in hot pan 3–4 min.', 'Pour over: 3 tbsp soy, 1 tbsp honey, 1 tsp sesame oil, garlic.', 'Toss on high heat 1–2 min until glazed. Serve over rice.'],
    prep_time_min: 5,
    cook_time_min: 18,
    total_time_min: 23,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['lunch', 'dinner', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['chicken', 'rice', 'teriyaki', 'high-protein'],
    total_calories: 580,
    total_protein: 52,
    total_carbs: 68,
    total_fat: 8,
    estimated_price_chf: 6.80,
    protein_efficiency: 9.0,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-9',
    name: 'Spicy Sriracha Chicken Fried Rice',
    category: 'dinner',
    description: 'High-heat fried rice with egg and chicken. 50g protein, crispy bits.',
    image_url: null,
    instructions: ['Cook and cool rice first (or use day-old).', 'Dice chicken, fry in very hot pan 3–4 min. Remove.', 'Scramble 2 eggs quickly in same pan — 30 seconds.', 'Add rice, toss on max heat 2 min.', 'Return chicken. Season: 2 tbsp soy, 1 tbsp sriracha, splash sesame oil.'],
    prep_time_min: 5,
    cook_time_min: 20,
    total_time_min: 25,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['dinner', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['chicken', 'fried-rice', 'spicy', 'egg', 'high-protein'],
    total_calories: 590,
    total_protein: 50,
    total_carbs: 62,
    total_fat: 12,
    estimated_price_chf: 6.20,
    protein_efficiency: 8.5,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-10',
    name: 'Garlic Butter Chicken Pasta',
    category: 'dinner',
    description: 'Pan-fried chicken in garlic butter sauce with pasta. 50g protein.',
    image_url: null,
    instructions: ['Boil 120g pasta in salted water. Reserve a cup of pasta water before draining.', 'Season and pan-fry chicken 5–6 min per side. Rest 2 min, slice.', 'In same pan: melt butter, fry 3 garlic cloves 30 sec.', 'Add pasta water splash, toss in pasta and chicken. Season.'],
    prep_time_min: 5,
    cook_time_min: 20,
    total_time_min: 25,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['dinner', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['chicken', 'pasta', 'garlic-butter', 'quick', 'high-protein'],
    total_calories: 610,
    total_protein: 50,
    total_carbs: 68,
    total_fat: 14,
    estimated_price_chf: 7.20,
    protein_efficiency: 8.2,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-11',
    name: 'Beef Bolognese with Penne',
    category: 'dinner',
    description: 'Real bolognese — brown the beef properly, simmer 10 min. 50g protein.',
    image_url: null,
    instructions: ['Brown 250g minced beef on high heat, breaking it up. 6–8 min.', 'Season: salt, pepper, oregano, garlic.', 'Add 200g chopped tomatoes + pinch of sugar. Simmer 10 min.', 'Cook 120g penne in salted water. Combine with sauce.'],
    prep_time_min: 5,
    cook_time_min: 20,
    total_time_min: 25,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['dinner'],
    stores_required: ['coop', 'migros'],
    tags: ['beef', 'pasta', 'bolognese', 'classic', 'high-protein'],
    total_calories: 680,
    total_protein: 50,
    total_carbs: 75,
    total_fat: 18,
    estimated_price_chf: 7.50,
    protein_efficiency: 7.4,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-12',
    name: 'Meal Prep Chicken Bowls (4 portions)',
    category: 'meal_prep',
    description: 'Cook once on Sunday. 4 full lunches: chicken, rice, veg. 54g protein each.',
    image_url: null,
    instructions: ['Cook 400g rice. Marinate 4 chicken breasts: soy, oil, garlic powder, paprika.', 'Pan-fry in batches 5–6 min per side. Rest 3 min. Slice.', 'Microwave 400g frozen veg 4 min.', 'Divide into 4 containers: rice, sliced chicken, veg. Cool completely before sealing.', 'Reheat 2–3 min when needed.'],
    prep_time_min: 10,
    cook_time_min: 35,
    total_time_min: 45,
    servings: 4,
    equipment_required: ['pan', 'microwave'],
    suitable_contexts: ['meal', 'meal_prep'],
    suitable_times: ['lunch', 'dinner', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['meal-prep', 'chicken', 'rice', 'high-protein', '4-servings'],
    total_calories: 570,
    total_protein: 54,
    total_carbs: 62,
    total_fat: 7,
    estimated_price_chf: 4.50,
    protein_efficiency: 9.5,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
]
