/**
 * Demo data — hardcoded, no Supabase, no private user data.
 * Used only by /demo/* routes.
 */
import type { Recipe, NutritionTargets } from '@/types'

// ── DEMO PRODUCTS ─────────────────────────────────────────────────────────────
// Real products scraped from coop.ch and migros.ch — public data

export interface DemoProduct {
  id: string
  name: string
  brand: string
  store: 'coop' | 'migros'
  category: string
  image_url: string
  product_page_url: string
  price_chf: number
  price_unit: string
  calories_per_100g: number
  protein_per_100g: number
  carbs_per_100g: number
  fat_per_100g: number
  package_size: string
  tags: string[]
}

export const DEMO_PRODUCTS: DemoProduct[] = [
  {
    id: 'dp-1',
    name: 'Thon rosé naturel',
    brand: 'Coop',
    store: 'coop',
    category: 'Fish',
    image_url: 'https://www.coop.ch/img/produkte/737_737/RGB/3950233_001.jpg',
    product_page_url: 'https://www.coop.ch/de/lebensmittel/vorraete/konserven/fisch/thunfisch-ohne-oel/thon-rose-naturel/p/3950233',
    price_chf: 1.95,
    price_unit: '155g',
    calories_per_100g: 110,
    protein_per_100g: 26,
    carbs_per_100g: 0,
    fat_per_100g: 0.7,
    package_size: '155g drained / 200g net',
    tags: ['high-protein', 'no-cook', 'cheap', 'emergency-protein'],
  },
  {
    id: 'dp-2',
    name: 'Naturafarm Pouletbrust',
    brand: 'Naturafarm',
    store: 'coop',
    category: 'Chicken',
    image_url: 'https://www.coop.ch/img/produkte/737_737/RGB/3066950_001.jpg',
    product_page_url: 'https://www.coop.ch/de/lebensmittel/fleisch-fisch/abgepacktes-frischfleisch/gefluegel/naturafarm-pouletbrust-2-stueck-ca/p/3066950',
    price_chf: 12.20,
    price_unit: 'ca. 220g',
    calories_per_100g: 109,
    protein_per_100g: 25,
    carbs_per_100g: 0,
    fat_per_100g: 1,
    package_size: 'ca. 220g (2 pieces)',
    tags: ['high-protein', 'chicken', 'lean'],
  },
  {
    id: 'dp-3',
    name: 'Skyr Natur',
    brand: 'Coop',
    store: 'coop',
    category: 'Dairy',
    image_url: 'https://www.coop.ch/img/produkte/737_737/RGB/6622281_001.jpg',
    product_page_url: 'https://www.coop.ch/de/lebensmittel/milchprodukte-eier/joghurt/joghurt-nature/skyr-natur/p/6622281',
    price_chf: 2.95,
    price_unit: '400g',
    calories_per_100g: 58,
    protein_per_100g: 11,
    carbs_per_100g: 3.5,
    fat_per_100g: 0,
    package_size: '400g',
    tags: ['high-protein', 'skyr', 'snack', 'no-cook'],
  },
  {
    id: 'dp-4',
    name: 'Prix Garantie Magerquark',
    brand: 'Prix Garantie',
    store: 'coop',
    category: 'Dairy',
    image_url: 'https://www.coop.ch/img/produkte/737_737/RGB/6568630_001.jpg',
    product_page_url: 'https://www.coop.ch/de/lebensmittel/milchprodukte-eier/quark/quark-nature/prix-garantie-magerquark/p/6568630',
    price_chf: 1.25,
    price_unit: '500g',
    calories_per_100g: 62,
    protein_per_100g: 11,
    carbs_per_100g: 4,
    fat_per_100g: 0.2,
    package_size: '500g',
    tags: ['high-protein', 'quark', 'cheap', 'no-cook'],
  },
  {
    id: 'dp-5',
    name: 'Optigal Pouletbrust',
    brand: 'Optigal',
    store: 'migros',
    category: 'Chicken',
    image_url: 'https://image.migros.ch/d/mo-boxed/v-w-1000-h-1000/o-af-1-t.clr-fff/0656119f4441c8e0e766f0a079dd42bdc6cd9084/optigal-pouletbrust.jpg',
    product_page_url: 'https://www.migros.ch/de/product/231525586000',
    price_chf: 3.20,
    price_unit: 'per 100g',
    calories_per_100g: 92,
    protein_per_100g: 20,
    carbs_per_100g: 0.6,
    fat_per_100g: 1,
    package_size: 'per 100g (sold loose)',
    tags: ['high-protein', 'chicken', 'lean'],
  },
  {
    id: 'dp-6',
    name: 'You Skyr Magerquark Nature',
    brand: 'You',
    store: 'migros',
    category: 'Dairy',
    image_url: 'https://image.migros.ch/d/mo-boxed/v-w-1000-h-1000/o-af-1-t.clr-fff/eb015519058c0be29288132fb260f267ee6dbcd2/you-skyr-magerquark-nature.jpg',
    product_page_url: 'https://www.migros.ch/de/product/205223900000',
    price_chf: 1.80,
    price_unit: '170g',
    calories_per_100g: 61,
    protein_per_100g: 12,
    carbs_per_100g: 2.9,
    fat_per_100g: 0.5,
    package_size: '170g',
    tags: ['high-protein', 'skyr', 'snack', 'no-cook', 'cheap'],
  },
  {
    id: 'dp-7',
    name: 'Migros Rosa Thon in Salzwasser',
    brand: 'Migros',
    store: 'migros',
    category: 'Fish',
    image_url: 'https://image.migros.ch/d/mo-boxed/v-w-1000-h-1000/o-af-1-t.clr-fff/6fd4c0674523286bc06f61c51ac894468889a8b1/migros-rosa-thon-in-salzwasser.jpg',
    product_page_url: 'https://www.migros.ch/de/product/155133700000',
    price_chf: 5.40,
    price_unit: '4×155g',
    calories_per_100g: 105,
    protein_per_100g: 25,
    carbs_per_100g: 0,
    fat_per_100g: 0.6,
    package_size: '4×155g multipack',
    tags: ['high-protein', 'tuna', 'no-cook', 'emergency-protein'],
  },
  {
    id: 'dp-8',
    name: 'M-Budget Magerquark',
    brand: 'M-Budget',
    store: 'migros',
    category: 'Dairy',
    image_url: 'https://image.migros.ch/d/mo-boxed/v-w-1000-h-1000/o-af-1-t.clr-fff/172505f62b577283ae4bb49514b0545a565277d1/m-budget-magerquark.jpg',
    product_page_url: 'https://www.migros.ch/de/product/200803100000',
    price_chf: 1.25,
    price_unit: '500g',
    calories_per_100g: 63,
    protein_per_100g: 9.7,
    carbs_per_100g: 5.7,
    fat_per_100g: 0.5,
    package_size: '500g',
    tags: ['protein', 'quark', 'cheap', 'no-cook'],
  },
  {
    id: 'dp-9',
    name: 'Naturafarm Eier Freilandhaltung',
    brand: 'Naturafarm',
    store: 'coop',
    category: 'Eggs',
    image_url: 'https://www.coop.ch/img/produkte/737_737/RGB/3407653_001.jpg',
    product_page_url: 'https://www.coop.ch/de/lebensmittel/milchprodukte-eier/eier/eier-roh/naturafarm-eier-aus-freilandhaltung-53g-10-stueck/p/3407653',
    price_chf: 6.30,
    price_unit: '10 Stück',
    calories_per_100g: 151,
    protein_per_100g: 13,
    carbs_per_100g: 0,
    fat_per_100g: 11,
    package_size: '10 eggs à 53g',
    tags: ['eggs', 'protein', 'breakfast'],
  },
  {
    id: 'dp-10',
    name: 'Pancho Villa Tortillas Weizen',
    brand: 'Pancho Villa',
    store: 'migros',
    category: 'Carbs',
    image_url: 'https://image.migros.ch/d/mo-boxed/v-w-1000-h-1000/o-af-1-t.clr-fff/2cb1551167f6a82e8f7e681338942eb0997c5811/pancho-villa-tortillas-weizen-super-soft-flexible.jpg',
    product_page_url: 'https://www.migros.ch/de/product/158567200000',
    price_chf: 4.55,
    price_unit: '326g',
    calories_per_100g: 299,
    protein_per_100g: 9,
    carbs_per_100g: 53,
    fat_per_100g: 5,
    package_size: '326g (8 wraps)',
    tags: ['wraps', 'carbs'],
  },
  {
    id: 'dp-11',
    name: 'Hirz Hüttenkäse Nature',
    brand: 'Hirz',
    store: 'coop',
    category: 'Dairy',
    image_url: 'https://www.coop.ch/img/produkte/737_737/RGB/3081176_001.jpg',
    product_page_url: 'https://www.coop.ch/de/lebensmittel/milchprodukte-eier/abgepackter-kaese/frischkaese-mozzarella/huettenkaese/hirz-huettenkaese-nature/p/3081176',
    price_chf: 1.95,
    price_unit: '200g',
    calories_per_100g: 95,
    protein_per_100g: 10.9,
    carbs_per_100g: 3.7,
    fat_per_100g: 4,
    package_size: '200g',
    tags: ['cottage-cheese', 'protein', 'snack', 'no-cook'],
  },
  {
    id: 'dp-12',
    name: 'Migros Cottage Cheese Nature',
    brand: 'Migros',
    store: 'migros',
    category: 'Dairy',
    image_url: 'https://image.migros.ch/d/mo-boxed/v-w-1000-h-1000/o-af-1-t.clr-fff/51914125b4c156003946f6d244b9305bec08fdb4/migros-cottage-cheese-nature.jpg',
    product_page_url: 'https://www.migros.ch/de/product/200604100000',
    price_chf: 1.80,
    price_unit: '200g',
    calories_per_100g: 87,
    protein_per_100g: 10,
    carbs_per_100g: 2.7,
    fat_per_100g: 4,
    package_size: '200g',
    tags: ['cottage-cheese', 'protein', 'snack', 'no-cook'],
  },
  // ── CARB BASES ───────────────────────────────────────────────────────────────
  {
    id: 'dp-13',
    name: 'Prix Garantie Langkornreis Parboiled',
    brand: 'Prix Garantie',
    store: 'coop',
    category: 'Carbs',
    image_url: 'https://www.coop.ch/img/produkte/737_737/RGB/6554390_001.jpg',
    product_page_url: 'https://www.coop.ch/de/lebensmittel/vorraete/grundnahrungsmittel/reis/langkorn-vitamin-camolino/prix-garantie-langkornreis-parboiled/p/6554390',
    price_chf: 1.35,
    price_unit: '1000g',
    calories_per_100g: 341,
    protein_per_100g: 7,
    carbs_per_100g: 77,
    fat_per_100g: 0,
    package_size: '1000g',
    tags: ['rice', 'carbs', 'cheap'],
  },
  {
    id: 'dp-14',
    name: 'Alnatura Himalaya Basmati Reis Bio',
    brand: 'Alnatura',
    store: 'migros',
    category: 'Carbs',
    image_url: 'https://image.migros.ch/d/mo-boxed/v-w-1000-h-1000/o-af-1-t.clr-fff/bb9d91c26bee6a26a0ced636cf5c4dbbbdd7d67a/alnatura-bio-himalaya-basmati-reis.jpg',
    product_page_url: 'https://www.migros.ch/de/product/104464300000',
    price_chf: 2.00,
    price_unit: '500g',
    calories_per_100g: 350,
    protein_per_100g: 8.6,
    carbs_per_100g: 75,
    fat_per_100g: 1.2,
    package_size: '500g',
    tags: ['rice', 'carbs'],
  },
  {
    id: 'dp-15',
    name: 'Prix Garantie Spaghetti',
    brand: 'Prix Garantie',
    store: 'coop',
    category: 'Carbs',
    image_url: 'https://www.coop.ch/img/produkte/737_737/RGB/7362486_001.jpg',
    product_page_url: 'https://www.coop.ch/de/lebensmittel/vorraete/grundnahrungsmittel/teigwaren/spaghetti/prix-garantie-spaghetti/p/7362486',
    price_chf: 1.20,
    price_unit: '1000g',
    calories_per_100g: 350,
    protein_per_100g: 12,
    carbs_per_100g: 71,
    fat_per_100g: 1.2,
    package_size: '1000g',
    tags: ['pasta', 'carbs', 'cheap'],
  },
  {
    id: 'dp-16',
    name: 'Migros Penne',
    brand: 'Migros',
    store: 'migros',
    category: 'Carbs',
    image_url: 'https://image.migros.ch/d/mo-boxed/v-w-1000-h-1000/o-af-1-t.clr-fff/d1b7826cd41749179d066cb0c8dfb2968ac4971d/migros-penne.jpg',
    product_page_url: 'https://www.migros.ch/de/product/104101600000',
    price_chf: 1.20,
    price_unit: '1000g',
    calories_per_100g: 349,
    protein_per_100g: 12,
    carbs_per_100g: 70,
    fat_per_100g: 1.5,
    package_size: '1000g',
    tags: ['pasta', 'carbs', 'cheap'],
  },
  {
    id: 'dp-17',
    name: 'Prix Garantie Toast dunkel',
    brand: 'Prix Garantie',
    store: 'coop',
    category: 'Bread',
    image_url: 'https://www.coop.ch/img/produkte/737_737/RGB/7302187_001.jpg',
    product_page_url: 'https://www.coop.ch/de/lebensmittel/brot-backwaren/haltbare-brote/toastbrote-buns/prix-garantie-toast-dunkel/p/7302187',
    price_chf: 1.20,
    price_unit: '500g',
    calories_per_100g: 259,
    protein_per_100g: 9.1,
    carbs_per_100g: 46,
    fat_per_100g: 3.2,
    package_size: '500g',
    tags: ['bread', 'toast', 'carbs', 'cheap'],
  },
  {
    id: 'dp-18',
    name: 'Migros Toast Vollkorn IP-SUISSE',
    brand: 'Migros',
    store: 'migros',
    category: 'Bread',
    image_url: 'https://image.migros.ch/d/mo-boxed/v-w-1000-h-1000/o-af-1-t.clr-fff/301ca29516574e5cba8a119b18cffcd506dfcfba/migros-ip-suisse-toast-vollkorn.jpg',
    product_page_url: 'https://www.migros.ch/de/product/111282200000',
    price_chf: 2.25,
    price_unit: '280g',
    calories_per_100g: 243,
    protein_per_100g: 10,
    carbs_per_100g: 38,
    fat_per_100g: 3.8,
    package_size: '280g',
    tags: ['bread', 'toast', 'carbs'],
  },
  // ── ADDITIONAL PROTEIN ────────────────────────────────────────────────────────
  {
    id: 'dp-19',
    name: 'Bio Eier Freiland 10 Stück',
    brand: 'Migros Bio',
    store: 'migros',
    category: 'Eggs',
    image_url: 'https://image.migros.ch/d/mo-boxed/v-w-1000-h-1000/o-af-1-t.clr-fff/56791370338b8d77e28fd175194591e8e5ad19d9/bio-eier-53-import-freiland.jpg',
    product_page_url: 'https://www.migros.ch/de/product/196570001000',
    price_chf: 4.80,
    price_unit: '10 Stück à 53g',
    calories_per_100g: 153,
    protein_per_100g: 13,
    carbs_per_100g: 0.6,
    fat_per_100g: 11,
    package_size: '10 eggs à 53g',
    tags: ['eggs', 'protein', 'breakfast'],
  },
  {
    id: 'dp-20',
    name: 'Migros Pouletschnitzel à la Minute',
    brand: 'Migros',
    store: 'migros',
    category: 'Chicken',
    image_url: 'https://image.migros.ch/d/mo-boxed/v-w-1000-h-1000/o-af-1-t.clr-fff/6fd727078886b5b07ceddbe22c0c0e848524c32b/migros-pouletschnitzel-a-la-minute.jpg',
    product_page_url: 'https://www.migros.ch/de/product/243100550000',
    price_chf: 8.00,
    price_unit: '500g',
    calories_per_100g: 118,
    protein_per_100g: 25,
    carbs_per_100g: 0,
    fat_per_100g: 2,
    package_size: '500g',
    tags: ['chicken', 'high-protein', 'lean'],
  },
  {
    id: 'dp-21',
    name: 'isey Skyr Nature laktosefrei',
    brand: 'isey',
    store: 'coop',
    category: 'Dairy',
    image_url: 'https://www.coop.ch/img/produkte/737_737/RGB/4846718_001.jpg',
    product_page_url: 'https://www.coop.ch/de/lebensmittel/milchprodukte-eier/quark/quark-nature/isey-skyr-nature-laktosefrei/p/4846718',
    price_chf: 2.05,
    price_unit: '170g',
    calories_per_100g: 61,
    protein_per_100g: 11,
    carbs_per_100g: 3.7,
    fat_per_100g: 0.2,
    package_size: '170g',
    tags: ['skyr', 'high-protein', 'snack', 'no-cook', 'lactose-free'],
  },
]

// ── PRODUCT LOOKUP BY ID ──────────────────────────────────────────────────────
export const DEMO_PRODUCT_MAP: Record<string, DemoProduct> =
  Object.fromEntries(DEMO_PRODUCTS.map(p => [p.id, p]))

// ── DEMO SHOPPING LIST ────────────────────────────────────────────────────────

export interface DemoShoppingItem {
  id: string
  product: DemoProduct
  quantity_g: number
  checked: boolean
  for_recipe: string
}

export const DEMO_SHOPPING_LIST: DemoShoppingItem[] = [
  // dp-2  = Coop Naturafarm Pouletbrust (CHF 12.20 / ca. 220g)
  { id: 'si-1', product: DEMO_PRODUCT_MAP['dp-2'],  quantity_g: 200, checked: false, for_recipe: 'Chicken Teriyaki' },
  // dp-13 = Coop Langkornreis (CHF 1.35 / 1000g)
  { id: 'si-2', product: DEMO_PRODUCT_MAP['dp-13'], quantity_g: 150, checked: false, for_recipe: 'Chicken Teriyaki' },
  // dp-3  = Coop Skyr Natur (CHF 2.95 / 400g)
  { id: 'si-3', product: DEMO_PRODUCT_MAP['dp-3'],  quantity_g: 150, checked: false, for_recipe: 'Skyr Berry Parfait' },
  // dp-1  = Coop Thon rosé (CHF 1.95 / 155g drained)
  { id: 'si-4', product: DEMO_PRODUCT_MAP['dp-1'],  quantity_g: 155, checked: true,  for_recipe: 'Tuna Melt on Toast' },
  // dp-17 = Coop Toast dunkel (CHF 1.20 / 500g)
  { id: 'si-5', product: DEMO_PRODUCT_MAP['dp-17'], quantity_g: 80,  checked: true,  for_recipe: 'Tuna Melt on Toast' },
  // dp-9  = Coop Naturafarm Eier (CHF 6.30 / 10 Stück à 53g) — 2 eggs = 106g
  { id: 'si-6', product: DEMO_PRODUCT_MAP['dp-9'],  quantity_g: 106, checked: false, for_recipe: 'Scrambled Eggs' },
  // dp-10 = Migros Pancho Villa Tortillas (CHF 4.55 / 326g) — 1 wrap ≈ 40g
  { id: 'si-7', product: DEMO_PRODUCT_MAP['dp-10'], quantity_g: 40,  checked: false, for_recipe: 'Greek Chicken Wrap' },
  // dp-4  = Coop Magerquark (CHF 1.25 / 500g)
  { id: 'si-8', product: DEMO_PRODUCT_MAP['dp-4'],  quantity_g: 250, checked: false, for_recipe: 'Quark Choc Mousse' },
]

export const DEMO_TARGETS: NutritionTargets = {
  calories: 2070,
  protein_min: 130,
  protein_target: 160,
  protein_max: 180,
}

// Realistic recipes spanning 200–700 kcal so calorie band filtering is obvious
export const DEMO_RECIPES: Recipe[] = [
  {
    id: 'demo-1',
    name: 'Emergency Max Protein',
    category: 'snack',
    description: 'Tuna + skyr side by side. 46g protein in under 300 kcal.',
    image_url: null,
    instructions: ['Drain tuna tin.', 'Spoon 200g skyr next to it.', 'Season with pepper and lemon.', 'Eat.'],
    prep_time_min: 2,
    cook_time_min: 0,
    total_time_min: 0,
    servings: 1,
    equipment_required: [],
    suitable_contexts: ['emergency_protein', 'snack', 'no_cooking'],
    suitable_times: ['post_gym', 'late_night'],
    stores_required: ['coop', 'migros'],
    tags: ['emergency-protein', 'no-cook', 'high-protein'],
    total_calories: 275,
    total_protein: 46,
    total_carbs: 8,
    total_fat: 2,
    estimated_price_chf: 4.20,
    protein_efficiency: 16.7,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-2',
    name: 'Quark Chocolate Mousse',
    category: 'snack',
    description: 'Magerquark with cocoa and honey. Tastes like dessert, 26g protein.',
    image_url: null,
    instructions: ['Mix 250g Magerquark with 1.5 tbsp cocoa, 2 tsp honey, pinch of salt.', 'Stir until smooth.', 'Top with raspberries.'],
    prep_time_min: 3,
    cook_time_min: 0,
    total_time_min: 0,
    servings: 1,
    equipment_required: [],
    suitable_contexts: ['snack', 'sweet', 'no_cooking'],
    suitable_times: ['late_night', 'breakfast'],
    stores_required: ['coop', 'migros'],
    tags: ['quark', 'sweet', 'no-cook', 'high-protein'],
    total_calories: 240,
    total_protein: 26,
    total_carbs: 28,
    total_fat: 3,
    estimated_price_chf: 2.80,
    protein_efficiency: 10.8,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-3',
    name: 'Skyr Berry Parfait',
    category: 'snack',
    description: 'Skyr layered with berries and granola. High protein, actually enjoyable.',
    image_url: null,
    instructions: ['Layer 150g skyr in a glass.', 'Add frozen berries (microwaved 30 sec).', 'Top with a handful of granola.', 'Drizzle with honey.'],
    prep_time_min: 3,
    cook_time_min: 0,
    total_time_min: 0,
    servings: 1,
    equipment_required: ['microwave'],
    suitable_contexts: ['snack', 'sweet', 'no_cooking'],
    suitable_times: ['breakfast', 'lunch'],
    stores_required: ['coop', 'migros'],
    tags: ['skyr', 'sweet', 'no-cook', 'high-protein'],
    total_calories: 320,
    total_protein: 28,
    total_carbs: 38,
    total_fat: 4,
    estimated_price_chf: 4.20,
    protein_efficiency: 8.8,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-4',
    name: 'Tuna Melt on Toast',
    category: 'lunch',
    description: 'Tuna with melted cheese on toast, grilled 3 minutes. 42g protein.',
    image_url: null,
    instructions: ['Mix drained tuna with a squeeze of lemon, salt, pepper.', 'Spread on 2 slices of toast.', 'Top with cheese slices.', 'Grill 3 min until bubbling.'],
    prep_time_min: 4,
    cook_time_min: 4,
    total_time_min: 8,
    servings: 1,
    equipment_required: ['oven'],
    suitable_contexts: ['meal', 'snack'],
    suitable_times: ['lunch', 'late_night'],
    stores_required: ['coop', 'migros'],
    tags: ['tuna', 'toast', 'quick', 'high-protein'],
    total_calories: 410,
    total_protein: 42,
    total_carbs: 28,
    total_fat: 12,
    estimated_price_chf: 4.80,
    protein_efficiency: 10.2,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-5',
    name: 'Creamy Scrambled Eggs on Toast',
    category: 'breakfast',
    description: 'Slow-cooked silky eggs on toast. 30g protein, 7 minutes.',
    image_url: null,
    instructions: ['Crack 4–5 eggs into a cold pan with butter and salt.', 'Medium-low heat — stir constantly until soft curds form (4–5 min).', 'Pull off heat when still slightly wet.', 'Serve on 2 slices of toast.'],
    prep_time_min: 1,
    cook_time_min: 6,
    total_time_min: 7,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['breakfast', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['eggs', 'breakfast', 'quick', 'high-protein'],
    total_calories: 380,
    total_protein: 30,
    total_carbs: 24,
    total_fat: 16,
    estimated_price_chf: 3.50,
    protein_efficiency: 7.9,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-6',
    name: 'Protein Pancakes',
    category: 'breakfast',
    description: 'Oat and skyr pancakes that taste like real pancakes. 40g protein.',
    image_url: null,
    instructions: ['Blend 80g oats, 3 eggs, 150g skyr, 0.5 tsp baking powder, pinch of salt.', 'Cook in an oiled pan on medium heat, 2–3 min per side.', 'Serve with yoghurt, honey, berries.'],
    prep_time_min: 5,
    cook_time_min: 12,
    total_time_min: 17,
    servings: 1,
    equipment_required: ['pan', 'blender'],
    suitable_contexts: ['meal'],
    suitable_times: ['breakfast', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['pancakes', 'breakfast', 'high-protein', 'skyr'],
    total_calories: 490,
    total_protein: 40,
    total_carbs: 52,
    total_fat: 10,
    estimated_price_chf: 4.50,
    protein_efficiency: 8.2,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-7',
    name: 'Greek Chicken Wrap',
    category: 'lunch',
    description: 'Marinated chicken with garlic skyr sauce in a tortilla. 48g protein.',
    image_url: null,
    instructions: ['Coat sliced chicken in oregano, paprika, lemon, oil. Pan-fry 5 min.', 'Mix skyr with garlic, lemon, salt for the sauce.', 'Warm tortilla 30 sec in dry pan.', 'Spread sauce, add chicken, cucumber, tomato. Roll and cut.'],
    prep_time_min: 8,
    cook_time_min: 8,
    total_time_min: 16,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['lunch', 'dinner'],
    stores_required: ['coop', 'migros'],
    tags: ['chicken', 'wrap', 'greek', 'quick', 'high-protein'],
    total_calories: 530,
    total_protein: 48,
    total_carbs: 44,
    total_fat: 12,
    estimated_price_chf: 6.40,
    protein_efficiency: 9.1,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-8',
    name: 'Chicken Teriyaki Rice Bowl',
    category: 'dinner',
    description: 'Sticky teriyaki chicken on rice. Made from scratch in 23 minutes. 52g protein.',
    image_url: null,
    instructions: ['Cook 150g rice (bring to boil, lid on, lowest heat, 12 min).', 'Slice chicken, fry in hot pan 3–4 min.', 'Pour over: 3 tbsp soy, 1 tbsp honey, 1 tsp sesame oil, garlic.', 'Toss on high heat 1–2 min until glazed. Serve over rice.'],
    prep_time_min: 5,
    cook_time_min: 18,
    total_time_min: 23,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['lunch', 'dinner', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['chicken', 'rice', 'teriyaki', 'high-protein'],
    total_calories: 580,
    total_protein: 52,
    total_carbs: 68,
    total_fat: 8,
    estimated_price_chf: 6.80,
    protein_efficiency: 9.0,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-9',
    name: 'Spicy Sriracha Chicken Fried Rice',
    category: 'dinner',
    description: 'High-heat fried rice with egg and chicken. 50g protein, crispy bits.',
    image_url: null,
    instructions: ['Cook and cool rice first (or use day-old).', 'Dice chicken, fry in very hot pan 3–4 min. Remove.', 'Scramble 2 eggs quickly in same pan — 30 seconds.', 'Add rice, toss on max heat 2 min.', 'Return chicken. Season: 2 tbsp soy, 1 tbsp sriracha, splash sesame oil.'],
    prep_time_min: 5,
    cook_time_min: 20,
    total_time_min: 25,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['dinner', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['chicken', 'fried-rice', 'spicy', 'egg', 'high-protein'],
    total_calories: 590,
    total_protein: 50,
    total_carbs: 62,
    total_fat: 12,
    estimated_price_chf: 6.20,
    protein_efficiency: 8.5,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-10',
    name: 'Garlic Butter Chicken Pasta',
    category: 'dinner',
    description: 'Pan-fried chicken in garlic butter sauce with pasta. 50g protein.',
    image_url: null,
    instructions: ['Boil 120g pasta in salted water. Reserve a cup of pasta water before draining.', 'Season and pan-fry chicken 5–6 min per side. Rest 2 min, slice.', 'In same pan: melt butter, fry 3 garlic cloves 30 sec.', 'Add pasta water splash, toss in pasta and chicken. Season.'],
    prep_time_min: 5,
    cook_time_min: 20,
    total_time_min: 25,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['dinner', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['chicken', 'pasta', 'garlic-butter', 'quick', 'high-protein'],
    total_calories: 610,
    total_protein: 50,
    total_carbs: 68,
    total_fat: 14,
    estimated_price_chf: 7.20,
    protein_efficiency: 8.2,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-11',
    name: 'Beef Bolognese with Penne',
    category: 'dinner',
    description: 'Real bolognese — brown the beef properly, simmer 10 min. 50g protein.',
    image_url: null,
    instructions: ['Brown 250g minced beef on high heat, breaking it up. 6–8 min.', 'Season: salt, pepper, oregano, garlic.', 'Add 200g chopped tomatoes + pinch of sugar. Simmer 10 min.', 'Cook 120g penne in salted water. Combine with sauce.'],
    prep_time_min: 5,
    cook_time_min: 20,
    total_time_min: 25,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['dinner'],
    stores_required: ['coop', 'migros'],
    tags: ['beef', 'pasta', 'bolognese', 'classic', 'high-protein'],
    total_calories: 680,
    total_protein: 50,
    total_carbs: 75,
    total_fat: 18,
    estimated_price_chf: 7.50,
    protein_efficiency: 7.4,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'demo-12',
    name: 'Meal Prep Chicken Bowls (4 portions)',
    category: 'meal_prep',
    description: 'Cook once on Sunday. 4 full lunches: chicken, rice, veg. 54g protein each.',
    image_url: null,
    instructions: ['Cook 400g rice. Marinate 4 chicken breasts: soy, oil, garlic powder, paprika.', 'Pan-fry in batches 5–6 min per side. Rest 3 min. Slice.', 'Microwave 400g frozen veg 4 min.', 'Divide into 4 containers: rice, sliced chicken, veg. Cool completely before sealing.', 'Reheat 2–3 min when needed.'],
    prep_time_min: 10,
    cook_time_min: 35,
    total_time_min: 45,
    servings: 4,
    equipment_required: ['pan', 'microwave'],
    suitable_contexts: ['meal', 'meal_prep'],
    suitable_times: ['lunch', 'dinner', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['meal-prep', 'chicken', 'rice', 'high-protein', '4-servings'],
    total_calories: 570,
    total_protein: 54,
    total_carbs: 62,
    total_fat: 7,
    estimated_price_chf: 4.50,
    protein_efficiency: 9.5,
    times_selected: 0,
    active: true,
    created_at: '',
    updated_at: '',
  },
]
