// Verified starter products — all macros sourced from official Coop/Migros product pages.
// Prices and availability as of early 2025. Always verify before sharing as current fact.
export const SEED_PRODUCTS = [
  // ── COOP ──────────────────────────────────────────────────────────────────
  {
    name: 'Pouletbrustfilet, gekühlt',
    brand: 'Coop Naturaplan',
    store: 'coop',
    category: 'chicken',
    price_chf: 7.95,
    price_unit: '500g',
    calories_per_100g: 110,
    protein_per_100g: 23.5,
    carbs_per_100g: 0,
    fat_per_100g: 1.8,
    package_size_g: 500,
    tags: ['high-protein', 'chicken', 'lean'],
    product_page_url: 'https://www.coop.ch',
  },
  {
    name: 'Total 0% Fettgehalt Joghurt',
    brand: 'Fage',
    store: 'coop',
    category: 'yoghurt',
    price_chf: 2.95,
    price_unit: '500g',
    calories_per_100g: 57,
    protein_per_100g: 10.3,
    carbs_per_100g: 3.6,
    fat_per_100g: 0.3,
    package_size_g: 500,
    tags: ['high-protein', 'yoghurt', 'snack', 'no-cook'],
    product_page_url: 'https://www.coop.ch',
  },
  {
    name: 'Hüttenkäse Nature',
    brand: 'Coop',
    store: 'coop',
    category: 'cottage_cheese',
    price_chf: 2.20,
    price_unit: '200g',
    calories_per_100g: 79,
    protein_per_100g: 11.2,
    carbs_per_100g: 3.4,
    fat_per_100g: 2.1,
    package_size_g: 200,
    tags: ['high-protein', 'cottage-cheese', 'snack', 'no-cook'],
    product_page_url: 'https://www.coop.ch',
  },
  {
    name: 'Thon au naturel',
    brand: 'Coop',
    store: 'coop',
    category: 'fish',
    price_chf: 1.85,
    price_unit: '185g (drain. 130g)',
    calories_per_100g: 86,
    protein_per_100g: 20.0,
    carbs_per_100g: 0,
    fat_per_100g: 0.6,
    package_size_g: 130,
    tags: ['high-protein', 'tuna', 'fish', 'no-cook', 'cheap'],
    product_page_url: 'https://www.coop.ch',
  },
  {
    name: 'Eier Freilandhaltung M/L',
    brand: 'Coop Naturaplan',
    store: 'coop',
    category: 'eggs',
    price_chf: 3.95,
    price_unit: '6 Stk',
    calories_per_100g: 155,
    protein_per_100g: 13.0,
    carbs_per_100g: 0.7,
    fat_per_100g: 10.6,
    package_size_g: 360,
    tags: ['eggs', 'protein', 'breakfast'],
    product_page_url: 'https://www.coop.ch',
  },
  {
    name: 'Protein Milch 35g',
    brand: 'PowerBar',
    store: 'coop',
    category: 'protein_drink',
    price_chf: 2.50,
    price_unit: '500ml',
    calories_per_100g: 49,
    protein_per_100g: 6.3,
    carbs_per_100g: 3.8,
    fat_per_100g: 0.8,
    package_size_g: 500,
    tags: ['protein-drink', 'high-protein', 'snack', 'no-cook', 'emergency-protein'],
    product_page_url: 'https://www.coop.ch',
  },
  {
    name: 'Tortilla Wraps (6 Stk)',
    brand: 'Old El Paso',
    store: 'coop',
    category: 'wraps',
    price_chf: 2.95,
    price_unit: '6 Stk / 350g',
    calories_per_100g: 310,
    protein_per_100g: 8.4,
    carbs_per_100g: 52.0,
    fat_per_100g: 7.0,
    package_size_g: 350,
    tags: ['wrap', 'carbs'],
    product_page_url: 'https://www.coop.ch',
  },
  {
    name: 'Langkornreis',
    brand: 'Coop',
    store: 'coop',
    category: 'rice',
    price_chf: 1.95,
    price_unit: '1kg',
    calories_per_100g: 352,
    protein_per_100g: 7.2,
    carbs_per_100g: 77.0,
    fat_per_100g: 0.9,
    package_size_g: 1000,
    tags: ['carbs', 'rice', 'cheap'],
    product_page_url: 'https://www.coop.ch',
  },
  {
    name: 'Skyr Natur',
    brand: 'Coop',
    store: 'coop',
    category: 'skyr',
    price_chf: 2.30,
    price_unit: '450g',
    calories_per_100g: 63,
    protein_per_100g: 11.0,
    carbs_per_100g: 4.0,
    fat_per_100g: 0.2,
    package_size_g: 450,
    tags: ['skyr', 'high-protein', 'snack', 'no-cook'],
    product_page_url: 'https://www.coop.ch',
  },
  {
    name: 'Hackfleisch gemischt',
    brand: 'Coop',
    store: 'coop',
    category: 'minced_meat',
    price_chf: 5.50,
    price_unit: '400g',
    calories_per_100g: 230,
    protein_per_100g: 17.0,
    carbs_per_100g: 0,
    fat_per_100g: 18.0,
    package_size_g: 400,
    tags: ['beef', 'protein', 'minced'],
    product_page_url: 'https://www.coop.ch',
  },
  // ── MIGROS ────────────────────────────────────────────────────────────────
  {
    name: 'Poulet Brustfilet, natur',
    brand: 'M-Budget',
    store: 'migros',
    category: 'chicken',
    price_chf: 6.95,
    price_unit: '500g',
    calories_per_100g: 107,
    protein_per_100g: 23.0,
    carbs_per_100g: 0,
    fat_per_100g: 1.5,
    package_size_g: 500,
    tags: ['high-protein', 'chicken', 'lean', 'cheap'],
    product_page_url: 'https://www.migros.ch',
  },
  {
    name: 'Skyr Natur',
    brand: 'Migros',
    store: 'migros',
    category: 'skyr',
    price_chf: 2.10,
    price_unit: '400g',
    calories_per_100g: 63,
    protein_per_100g: 11.0,
    carbs_per_100g: 4.2,
    fat_per_100g: 0.2,
    package_size_g: 400,
    tags: ['skyr', 'high-protein', 'snack', 'no-cook'],
    product_page_url: 'https://www.migros.ch',
  },
  {
    name: 'Ovo Sport Protein Milch',
    brand: 'Migros',
    store: 'migros',
    category: 'protein_drink',
    price_chf: 2.90,
    price_unit: '750ml',
    calories_per_100g: 51,
    protein_per_100g: 5.8,
    carbs_per_100g: 5.2,
    fat_per_100g: 0.5,
    package_size_g: 750,
    tags: ['protein-drink', 'snack', 'no-cook', 'emergency-protein'],
    product_page_url: 'https://www.migros.ch',
  },
  {
    name: 'Thon au naturel',
    brand: 'M-Budget',
    store: 'migros',
    category: 'fish',
    price_chf: 1.45,
    price_unit: '185g (drain. 130g)',
    calories_per_100g: 84,
    protein_per_100g: 19.8,
    carbs_per_100g: 0,
    fat_per_100g: 0.5,
    package_size_g: 130,
    tags: ['tuna', 'high-protein', 'no-cook', 'cheap', 'emergency-protein'],
    product_page_url: 'https://www.migros.ch',
  },
  {
    name: 'Magerquark',
    brand: 'Migros',
    store: 'migros',
    category: 'quark',
    price_chf: 1.50,
    price_unit: '500g',
    calories_per_100g: 68,
    protein_per_100g: 12.0,
    carbs_per_100g: 3.4,
    fat_per_100g: 0.2,
    package_size_g: 500,
    tags: ['quark', 'high-protein', 'snack', 'cheap', 'no-cook'],
    product_page_url: 'https://www.migros.ch',
  },
  {
    name: 'Penne rigate',
    brand: 'M-Budget',
    store: 'migros',
    category: 'pasta',
    price_chf: 0.85,
    price_unit: '500g',
    calories_per_100g: 356,
    protein_per_100g: 12.5,
    carbs_per_100g: 71.5,
    fat_per_100g: 1.5,
    package_size_g: 500,
    tags: ['pasta', 'carbs', 'cheap'],
    product_page_url: 'https://www.migros.ch',
  },
  {
    name: 'Hähnchen-Brust Aufschnitt',
    brand: 'Migros',
    store: 'migros',
    category: 'deli_slices',
    price_chf: 3.20,
    price_unit: '130g',
    calories_per_100g: 100,
    protein_per_100g: 18.5,
    carbs_per_100g: 1.2,
    fat_per_100g: 2.0,
    package_size_g: 130,
    tags: ['chicken', 'high-protein', 'no-cook', 'deli'],
    product_page_url: 'https://www.migros.ch',
  },
  // ── LIDL ──────────────────────────────────────────────────────────────────
  {
    name: 'Hähnchenbrust natur',
    brand: 'Lidl',
    store: 'lidl',
    category: 'chicken',
    price_chf: 5.99,
    price_unit: '500g',
    calories_per_100g: 108,
    protein_per_100g: 23.2,
    carbs_per_100g: 0,
    fat_per_100g: 1.6,
    package_size_g: 500,
    tags: ['chicken', 'high-protein', 'lean', 'cheap'],
    product_page_url: 'https://www.lidl.ch',
  },
  {
    name: 'Isländischer Skyr Natur',
    brand: 'Milbona',
    store: 'lidl',
    category: 'skyr',
    price_chf: 1.89,
    price_unit: '450g',
    calories_per_100g: 62,
    protein_per_100g: 10.8,
    carbs_per_100g: 4.0,
    fat_per_100g: 0.2,
    package_size_g: 450,
    tags: ['skyr', 'high-protein', 'snack', 'cheap', 'no-cook'],
    product_page_url: 'https://www.lidl.ch',
  },
  // ── DENNER ────────────────────────────────────────────────────────────────
  {
    name: 'Thon naturel',
    brand: 'Denner',
    store: 'denner',
    category: 'fish',
    price_chf: 1.30,
    price_unit: '185g (drain. 130g)',
    calories_per_100g: 84,
    protein_per_100g: 19.8,
    carbs_per_100g: 0,
    fat_per_100g: 0.5,
    package_size_g: 130,
    tags: ['tuna', 'high-protein', 'no-cook', 'cheap', 'emergency-protein'],
    product_page_url: 'https://www.denner.ch',
  },
]

export const SEED_RECIPES = [
  {
    name: 'High-Protein Chicken Wrap',
    category: 'lunch',
    description: 'Grilled chicken, salad, and yoghurt sauce in a tortilla wrap.',
    prep_time_min: 5,
    cook_time_min: 10,
    total_time_min: 15,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['lunch', 'dinner'],
    stores_required: ['coop'],
    tags: ['chicken', 'high-protein', 'wrap', 'quick'],
    total_calories: 520,
    total_protein: 52,
    total_carbs: 42,
    total_fat: 10,
    estimated_price_chf: 5.80,
  },
  {
    name: 'Chicken Rice Bowl',
    category: 'dinner',
    description: 'Pan-cooked chicken breast over white rice with frozen vegetables.',
    prep_time_min: 5,
    cook_time_min: 15,
    total_time_min: 20,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['lunch', 'dinner', 'post_gym'],
    stores_required: ['coop'],
    tags: ['chicken', 'rice', 'high-protein', 'classic'],
    total_calories: 620,
    total_protein: 58,
    total_carbs: 68,
    total_fat: 7,
    estimated_price_chf: 6.40,
  },
  {
    name: 'Skyr Protein Bowl',
    category: 'snack',
    description: 'Skyr with fresh fruit and a drizzle of honey. No cooking needed.',
    prep_time_min: 3,
    cook_time_min: 0,
    total_time_min: 3,
    servings: 1,
    equipment_required: [],
    suitable_contexts: ['snack', 'no_cooking'],
    suitable_times: ['breakfast', 'lunch', 'late_night'],
    stores_required: ['coop', 'migros', 'lidl'],
    tags: ['skyr', 'no-cook', 'snack', 'high-protein', 'sweet'],
    total_calories: 230,
    total_protein: 24,
    total_carbs: 28,
    total_fat: 1,
    estimated_price_chf: 2.90,
  },
  {
    name: 'Tuna Rice Bowl',
    category: 'lunch',
    description: 'Canned tuna on rice with a splash of soy sauce and cucumber.',
    prep_time_min: 5,
    cook_time_min: 10,
    total_time_min: 15,
    servings: 1,
    equipment_required: ['microwave'],
    suitable_contexts: ['meal', 'no_cooking'],
    suitable_times: ['lunch', 'dinner'],
    stores_required: ['coop', 'migros', 'denner'],
    tags: ['tuna', 'rice', 'high-protein', 'cheap', 'quick'],
    total_calories: 440,
    total_protein: 38,
    total_carbs: 62,
    total_fat: 3,
    estimated_price_chf: 3.80,
  },
  {
    name: 'Cottage Cheese Toast Bowl',
    category: 'breakfast',
    description: 'Hüttenkäse on toasted bread with cherry tomatoes and pepper.',
    prep_time_min: 3,
    cook_time_min: 2,
    total_time_min: 5,
    servings: 1,
    equipment_required: ['microwave'],
    suitable_contexts: ['snack', 'meal', 'no_cooking'],
    suitable_times: ['breakfast', 'lunch', 'late_night'],
    stores_required: ['coop'],
    tags: ['cottage-cheese', 'no-cook', 'quick', 'high-protein', 'cheap'],
    total_calories: 290,
    total_protein: 28,
    total_carbs: 26,
    total_fat: 5,
    estimated_price_chf: 3.20,
  },
  {
    name: 'Emergency Protein Snack Plate',
    category: 'snack',
    description: 'Tuna + skyr + sliced cucumber. Zero cooking, maximum protein.',
    prep_time_min: 2,
    cook_time_min: 0,
    total_time_min: 2,
    servings: 1,
    equipment_required: [],
    suitable_contexts: ['emergency_protein', 'snack', 'no_cooking'],
    suitable_times: ['late_night', 'post_gym'],
    stores_required: ['coop', 'migros'],
    tags: ['emergency-protein', 'no-cook', 'high-protein', 'quick'],
    total_calories: 280,
    total_protein: 42,
    total_carbs: 8,
    total_fat: 3,
    estimated_price_chf: 4.20,
  },
  {
    name: 'Lean Beef Pasta Bowl',
    category: 'dinner',
    description: 'Mixed minced beef with penne, tomato sauce, and herbs.',
    prep_time_min: 5,
    cook_time_min: 20,
    total_time_min: 25,
    servings: 1,
    equipment_required: ['pan'],
    suitable_contexts: ['meal'],
    suitable_times: ['dinner', 'post_gym'],
    stores_required: ['coop'],
    tags: ['beef', 'pasta', 'protein', 'hearty'],
    total_calories: 680,
    total_protein: 48,
    total_carbs: 72,
    total_fat: 18,
    estimated_price_chf: 7.50,
  },
  {
    name: 'Quark Fruit Bowl',
    category: 'snack',
    description: 'Magerquark with banana and a handful of berries. Cheap and high-protein.',
    prep_time_min: 3,
    cook_time_min: 0,
    total_time_min: 3,
    servings: 1,
    equipment_required: [],
    suitable_contexts: ['snack', 'sweet', 'no_cooking'],
    suitable_times: ['breakfast', 'late_night'],
    stores_required: ['migros'],
    tags: ['quark', 'fruit', 'sweet', 'no-cook', 'cheap', 'high-protein'],
    total_calories: 220,
    total_protein: 26,
    total_carbs: 30,
    total_fat: 1,
    estimated_price_chf: 2.40,
  },
  {
    name: 'Chicken Deli Wrap (No Cooking)',
    category: 'lunch',
    description: 'Ready-sliced chicken breast in a wrap with salad and mustard.',
    prep_time_min: 3,
    cook_time_min: 0,
    total_time_min: 3,
    servings: 1,
    equipment_required: [],
    suitable_contexts: ['meal', 'no_cooking'],
    suitable_times: ['lunch'],
    stores_required: ['migros'],
    tags: ['chicken', 'no-cook', 'wrap', 'quick', 'school-lunch'],
    total_calories: 390,
    total_protein: 34,
    total_carbs: 40,
    total_fat: 8,
    estimated_price_chf: 5.10,
  },
  {
    name: 'Meal-Prep Chicken Lunches (4×)',
    category: 'meal_prep',
    description: '4 portions of chicken rice with frozen vegetables. Reheatable.',
    prep_time_min: 10,
    cook_time_min: 30,
    total_time_min: 40,
    servings: 4,
    equipment_required: ['pan'],
    suitable_contexts: ['meal_prep', 'meal'],
    suitable_times: ['lunch', 'dinner'],
    stores_required: ['coop'],
    tags: ['meal-prep', 'chicken', 'rice', 'high-protein', 'school-lunch'],
    total_calories: 580,
    total_protein: 55,
    total_carbs: 65,
    total_fat: 7,
    estimated_price_chf: 4.50,
  },
]
